environment:
  matrix:
    # does not work with sw at the moment
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      #platform: Win32
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      #platform: Win32
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      #platform: Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      platform: Win64

configuration:
  - Release

cache:
  - c:/Users/appveyor/.sw -> appveyor.yml

before_build:
  - curl -fsS -L -o dl.zip https://github.com/SoftwareNetwork/binaries/raw/master/sw-master-windows-client.zip
  - 7z x dl.zip
  - set PATH=%PATH%;%cd%

build_script:
  - sw -version
  # debug build causes long builds (> 1h), appveyor drops them
  - sw -show-output -platform %platform% -config r build -Dwith-tests=1
  # test
  - git clone https://github.com/egorpugin/tessdata tessdata_unittest123
  - sw -show-output -platform %platform% -config r test -Dwith-tests=1 -Dskip-tests=lstm.* -Dtest-data-dir=tessdata_unittest123

after_build:
  - 7z a tesseract.zip %APPVEYOR_BUILD_FOLDER%\.sw\out\**\*.exe %APPVEYOR_BUILD_FOLDER%\.sw\out\**\*.dll
  #- 7z a tesseract.zip %APPVEYOR_BUILD_FOLDER%\.sw\Windows_*_Shared_Release_MSVC_*\*.exe %APPVEYOR_BUILD_FOLDER%\.sw\Windows_*_Shared_Release_MSVC_*\*.dll

artifacts:
  - path: tesseract.zip
    name: tesseract-$(APPVEYOR_BUILD_VERSION)

